name: System Design Notes
description: A collection of System Design interview questions & their solutions
meta_description: 'A collection of System Design interview questions & their solutions'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://systemdesignprimer.com'
google_analytics: 'UA-XXXXXXXX-X'
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Details for the RSS feed generator
url: 'https://systemdesignprimer.com'
author: 'Pranav'

# Disqus config
disqus-shortname: 'system-design-primer'
